<?php

namespace LaravelExporter\Support;

/**
 * Report Header Configuration
 *
 * Fluent builder for configuring report headers including
 * company name, title, subtitle, date range, and metadata.
 */
class ReportHeader
{
    protected ?string $companyName = null;
    protected ?string $title = null;
    protected ?string $subtitle = null;
    protected ?string $dateRange = null;
    protected ?string $generatedBy = null;
    protected ?string $generatedAt = null;
    protected array $customRows = [];

    /**
     * Create a new report header
     */
    public static function make(): static
    {
        return new static();
    }

    /**
     * Set company name
     */
    public function company(string $name): static
    {
        $this->companyName = $name;
        return $this;
    }

    /**
     * Set report title
     */
    public function title(string $title): static
    {
        $this->title = $title;
        return $this;
    }

    /**
     * Set report subtitle
     */
    public function subtitle(string $subtitle): static
    {
        $this->subtitle = $subtitle;
        return $this;
    }

    /**
     * Set date range from strings
     */
    public function dateRange(string $from, string $to): static
    {
        $this->dateRange = "Period: {$from} to {$to}";
        return $this;
    }

    /**
     * Set date range from Carbon instances
     */
    public function dateRangeCarbon(\DateTimeInterface $from, \DateTimeInterface $to, string $format = 'd-M-Y'): static
    {
        return $this->dateRange(
            $from->format($format),
            $to->format($format)
        );
    }

    /**
     * Set single date (e.g., "As on 31-Mar-2024")
     */
    public function asOnDate(string $date): static
    {
        $this->dateRange = "As on: {$date}";
        return $this;
    }

    /**
     * Set generated by user
     */
    public function generatedBy(string $userName): static
    {
        $this->generatedBy = "Generated by: {$userName}";
        return $this;
    }

    /**
     * Set generated timestamp
     */
    public function generatedAt(?\DateTimeInterface $timestamp = null): static
    {
        $timestamp = $timestamp ?? new \DateTime();
        $this->generatedAt = "Generated on: " . $timestamp->format('d-M-Y H:i:s');
        return $this;
    }

    /**
     * Add a custom row to the header
     */
    public function addRow(string $text): static
    {
        $this->customRows[] = $text;
        return $this;
    }

    /**
     * Alias for addRow() - alternative naming
     */
    public function addLine(string $text): static
    {
        return $this->addRow($text);
    }

    /**
     * Get all header rows in order
     */
    public function getRows(): array
    {
        $rows = [];

        if ($this->companyName) {
            $rows[] = ['text' => $this->companyName, 'style' => 'company'];
        }

        if ($this->title) {
            $rows[] = ['text' => $this->title, 'style' => 'title'];
        }

        if ($this->subtitle) {
            $rows[] = ['text' => $this->subtitle, 'style' => 'subtitle'];
        }

        if ($this->dateRange) {
            $rows[] = ['text' => $this->dateRange, 'style' => 'info'];
        }

        foreach ($this->customRows as $row) {
            $rows[] = ['text' => $row, 'style' => 'custom'];
        }

        if ($this->generatedBy) {
            $rows[] = ['text' => $this->generatedBy, 'style' => 'meta'];
        }

        if ($this->generatedAt) {
            $rows[] = ['text' => $this->generatedAt, 'style' => 'meta'];
        }

        return $rows;
    }

    /**
     * Get the number of header rows
     */
    public function getRowCount(): int
    {
        return count($this->getRows());
    }

    /**
     * Check if header is empty
     */
    public function isEmpty(): bool
    {
        return $this->getRowCount() === 0;
    }

    /**
     * Convert to array
     */
    public function toArray(): array
    {
        return [
            'company_name' => $this->companyName,
            'title' => $this->title,
            'subtitle' => $this->subtitle,
            'date_range' => $this->dateRange,
            'generated_by' => $this->generatedBy,
            'generated_at' => $this->generatedAt,
            'custom_rows' => $this->customRows,
            'rows' => $this->getRows(),
        ];
    }
}
